package ai.rojan.backend.infrastructure.persistence.user

import ai.rojan.backend.domain.user.UserRole
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EntityListeners
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import jakarta.persistence.Table
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedDate
import org.springframework.data.jpa.domain.support.AuditingEntityListener
import java.time.Instant
import java.util.UUID

/**
 * Persistence model for [ai.rojan.backend.domain.user.User]. Deliberately
 * separate from the domain entity so JPA/Hibernate concerns never leak into
 * the domain layer; [UserRepositoryAdapter] maps between the two.
 *
 * Mobile-First Authentication Phase 1: [email]/[passwordHash] are now
 * nullable columns and [phoneNumber] is new — see
 * `V5__mobile_authentication.sql` for the matching schema change (including
 * the DB-level CHECK constraint mirroring this class's "email or phone
 * required" invariant, enforced authoritatively in the domain layer).
 *
 * The no-arg constructor JPA requires is generated by the kotlin-jpa
 * compiler plugin (see infrastructure/build.gradle.kts).
 */
@Entity
@Table(name = "users")
@EntityListeners(AuditingEntityListener::class)
class UserJpaEntity(
    @Id
    val id: UUID,

    @Column(unique = true)
    var email: String?,

    @Column(name = "password_hash")
    var passwordHash: String?,

    @Column(name = "phone_number", unique = true)
    var phoneNumber: String?,

    @Column(name = "full_name", nullable = false)
    var fullName: String,

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    var role: UserRole,

    @Column(nullable = false)
    var active: Boolean,

    // Phase 5A.2, User Profile Media: identity-slot references into
    // media_assets (mirrors salons.logo_media_id / cover_media_id).
    @Column(name = "avatar_media_id")
    var avatarMediaId: UUID? = null,

    @Column(name = "cover_media_id")
    var coverMediaId: UUID? = null,
) {
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    var createdAt: Instant? = null

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    var updatedAt: Instant? = null
}
